---
# tasks file for ansible-role-vault-authentication
- name: Add Our Root CA
  copy:
    src: root-ca.crt
    dest: /etc/pki/ca-trust/source/anchors/giffgaff.crt
  notify: update-ca-trust

- meta: flush_handlers


- name: Get pks7 certificate
  uri:
    url: http://169.254.169.254/latest/dynamic/instance-identity/pkcs7
    return_content: yes
  register: certificate_request

- debug:
    msg: Requesting Certificates for {{certificate_hostname}}

- name: Log the machine into vault
  uri:
    url: https://{{vault_address}}/v1/auth/aws-ec2/login
    method: POST
    body: "{\"role\":\"jenkins-server\", \"pkcs7\": \"{{certificate_request.content|replace('\n','')}}\", \"nonce\": \"{{ certificate_hostname | to_uuid }}\"}"
    body_format: json
    return_content: yes
  register: vault_auth_request

- name: Write Vault Token
  copy:
    dest: /root/.vault-token
    content: "{{(vault_auth_request.content|from_json)['auth']['client_token']}}"

- name: Request a server certificate
  uri:
    headers:
      X-Vault-Token: "{{(vault_auth_request.content|from_json)['auth']['client_token']}}"
    url: https://vault.aws.int.giffgaff.co.uk/v1/pki/issue/aws-int-giffgaff-shortlived-server
    method: POST
    body: |
        {
          "common_name": "{{certificate_hostname}}",
        }
    body_format: json
    return_content: yes
  register: vault_cert_request


- name: Write Keyfile
  copy:
    dest: /etc/pki/tls/private/{{certificate_hostname}}.pem
    content: "{{(vault_cert_request.content | from_json)['data']['private_key']}}"

- name: Write Certificate
  copy:
    dest: /etc/pki/tls/certs/{{certificate_hostname}}.pem
    content: "{{(vault_cert_request.content | from_json)['data']['certificate']}}"

- name: Request a wildcard server certificate
  uri:
    headers:
      X-Vault-Token: "{{(vault_auth_request.content|from_json)['auth']['client_token']}}"
    url: https://vault.aws.int.giffgaff.co.uk/v1/pki/issue/aws-int-giffgaff-shortlived-server
    method: POST
    body: |
        {
          "common_name": "*.{{certificate_hostname}}",
        }
    body_format: json
    return_content: yes
  register: vault_wildcard_cert_request


- name: Write Keyfile
  copy:
    dest: /etc/pki/tls/private/wildcard_{{certificate_hostname}}.pem
    content: "{{(vault_wildcard_cert_request.content | from_json)['data']['private_key']}}"

- name: Write Certificate
  copy:
    dest: /etc/pki/tls/certs/wildcard_{{certificate_hostname}}.pem
    content: "{{(vault_wildcard_cert_request.content | from_json)['data']['certificate']}}"