---

# See: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

- name: Install RubyGem
  yum:
    name: gem
    state: latest

- name: Download openshift client
  get_url:
    url: "{{ openshift_client_download_url }}"
    dest: "{{ openshift_download_dir }}"
    checksum: "{{ openshift_client_signature }}"

- name: Unpack openshift client
  unarchive:
    copy: no
    src: "{{ openshift_download_dir }}/{{ openshift_client_package_file }}"
    dest: "{{ openshift_download_dir }}"
    creates: "{{ openshift_client_unpackaged_dir }}/oc"

- name: Copy oc into bin dir
  copy:
    remote_src: yes
    src: "{{ openshift_download_dir }}/{{ openshift_client_unpackaged_dir }}/oc"
    dest: /usr/bin/oc
    owner: root
    group: root
    mode: 0755

- name: Check OC cluster status
  command: oc cluster status
  register: oc_status_result
  ignore_errors: true

- name: Create OC cluster
  command: "oc cluster up --public-hostname='{{ openshift_hostname }}' --host-data-dir /var/lib/origin/etcd.data.local --logging --metrics"
  when: "'OpenShift cluster is not running' in oc_status_result.stdout"

- name: Add AWS config
  lineinfile:
    dest: /var/lib/origin/openshift.local.config/master/master-config.yaml
    regexp: '\s\singressIPNetworkCIDR: (.*)'
    line: '#  ingressIPNetworkCIDR $1'

- name: Add AWS config
  lineinfile:
    dest: /var/lib/origin/openshift.local.config/master/master-config.yaml
    regexp: '\s\sapiServerArguments: null'
    line: '  apiServerArguments: {"cloud-provider": ["aws"]}'

- name: Add AWS config
  lineinfile:
    dest: /var/lib/origin/openshift.local.config/node-{{ansible_eth0.ipv4.address}}/node-config.yaml
    line: 'kubeletArguments: {"cloud-provider": ["aws"]}'

- name: Add AWS config
  lineinfile:
    dest: /var/lib/origin/openshift.local.config/master/master-config.yaml
    regexp: '\s\scontrollerArguments: null'
    line: '  controllerArguments: {"cloud-provider": ["aws"]}'

- name: regenerate our SSL certificates
  shell: oc adm ca create-server-cert --signer-cert=/var/lib/origin/openshift.local.config/master/ca.crt  --signer-key=/var/lib/origin/openshift.local.config/master/ca.key  --signer-serial=/var/lib/origin/openshift.local.config/master/ca.serial.txt  --hostnames=$(curl http://169.254.169.254/latest/meta-data/local-ipv4),127.0.0.1,172.17.0.1,$(curl http://169.254.169.254/latest/meta-data/local-hostname) --cert /var/lib/origin/openshift.local.config/node-$(curl http://169.254.169.254/latest/meta-data/local-ipv4)/server.crt --key /var/lib/origin/openshift.local.config/node-$(curl http://169.254.169.254/latest/meta-data/local-ipv4)/server.key
  when: "'OpenShift cluster is not running' in oc_status_result.stdout"

- name: Add GitHub auth configuration
  blockinfile:
    dest: /var/lib/origin/openshift.local.config/master/master-config.yaml
    insertafter: "identityProviders:"
    state: present
    block: |2
        - name: github
          challenge: false
          login: true
          mappingMethod: claim
          provider:
            apiVersion: v1
            kind: GitHubIdentityProvider
            clientID: {{ openshift_oauth_github_clientid }}
            clientSecret: {{ openshift_oauth_github_clientsecret }}
            organizations:
            - {{ openshift_oauth_github_organisation }}
  notify:
  - Restart OC cluster

